<?php
$CatTitles = array(
'1',    'Summary categories',
'2',    'Results by race/ethnicity',
'3',    'Results of socially disadvantaged',
'4',    'Parent education',
'5',    'Teacher characteristics',
'6',    'Subject performance',
'7',    'African American detailed information',
'8',    'American Indian detailed information',
'9',    'Asian detailed information',
'10',   'Filipino detailed information',
'11',   'Hispanic/Latino detailed information',
'12',   'Pacific Islander detailed information',
'13',   'White detailed information',
'14',   'Socioeconomically disadvantaged detailed',
'15',   'Student demographics',
);

$Category = array(
"1" => array(
'8'  => "API Score",
'9'  => "Percent of Students Tested",
"10" => "Number of Valid Tests",
'11' => "Statewide Rank",
'12' => "Similar Schools Rank",
'13' => "Next year Growth Target",
'14' => "Next year API Target",
'65' => "Multi-Track Year-Round School?",
'66' => "Percent of Students First Attending This School in Current Year",
'67' => "Average Class Size of Grades K-3",
'68' => "Average Class Size of Grades 4-6",
'69' => "Average Class Size of Core Academic Courses in Departmentalized Programs",
'80' => "Percent of Students First Attending This District in Current Year",
'81' => "School Characteristics Index",
'82' => "Charter School Indicator",
'83' => "Bridge School Indicator",
'84' => "Grade Type",
'85' => "API for Grade Type",
'86' => "Number Tested for Grade Type",
),

"2" => array(
'15' => "Number of African Americans Tested",
'17' => "African Americans API",
'18' => "Next year African Americans Growth Target",
'19' => "Next year African Americans API Target",
'20' => "Number of American Indians Tested",
'22' => "American Indians API",
'23' => "Next year American Indians Growth Target",
'24' => "Next year American Indians API Target",
'25' => "Number of Asians Tested",
'27' => "Asians API",
'28' => "Next year Asians Growth Target",
'29' => "Next year Asians API Target",
'30' => "Number of Filipinos Tested",
'32' => "Filipinos API",
'33' => "Next year Filipinos Growth Target",
'34' => "Next year Filipinos API Target",
'35' => "Number of Hispanics or Latinos Tested",
'37' => "Hispanics or Latinos API",
'38' => "Next year Hispanics or Latinos Growth Target",
'39' => "Next year Hispanics or Latinos API Target",
'40' => "Number of Pacific Islanders Tested",
'42' => "Pacific Islanders API",
'43' => "Next year Pacific Islanders Growth Target",
'44' => "Next year Pacific Islanders API Target",
'45' => "Number of White not Hispanic Tested",
'47' => "White not Hispanic API",
'48' => "Next year White not Hispanic Growth Target",
'49' => "Next year White not Hispanic API Target",
),

"4" => array(
'70' => "Percent of Students with Parent Education Data",
'71' => "Percent of Parent Education Data -- Not High School Graduate",
'72' => "Percent of Parent Education Data -- High School Graduate",
'73' => "Percent of Parent Education Data -- Some College",
'74' => "Percent of Parent Education Data -- College Graduate",
'75' => "Percent of Parent Education Data -- Graduate School",
'76' => "Average Parent Education Level",
),

"5" => array(
'77' => "Percent of Teachers with Full Credentials",
'78' => "Percent of Teachers with Emergency Credentials",
'79' => "Percent of Teachers with Full Credentials Less Percent of Teachers with Emergency Credentials",
),

"6" => array(
'87' => "Number of Students in Performance Band 1 array(lowest) in Reading",
'88' => "Number of Students in Performance Band 2 in Reading",
'89' => "Number of Students in Performance Band 3 in Reading",
'90' => "Number of Students in Performance Band 4 in Reading",
'91' => "Number of Students in Performance Band 5 array(highest) in Reading",
'1087' => "Percent Students in Performance Band 1 array(lowest) in Reading",
'1088' => "Percent Students in Performance Band 2 in Reading",
'1089' => "Percent Students in Performance Band 3 in Reading",
'1090' => "Percent Students in Performance Band 4 in Reading",
'1091' => "Percent Students in Performance Band 5 array(highest) in Reading",

'92' => "Number of Students in Performance Band 1 array(lowest) in Mathematics",
'93' => "Number of Students in Performance Band 2 in Mathematics",
'94' => "Number of Students in Performance Band 3 in Mathematics",
'95' => "Number of Students in Performance Band 4 in Mathematics",
'96' => "Number of Students in Performance Band 5 array(highest) in Mathematics",
'1092' => "Percent Students in Performance Band 1 array(lowest) in Mathematics",
'1093' => "Percent Students in Performance Band 2 in Mathematics",
'1094' => "Percent Students in Performance Band 3 in Mathematics",
'1095' => "Percent Students in Performance Band 4 in Mathematics",
'1096' => "Percent Students in Performance Band 5 array(highest) in Mathematics",

'97' => "Number of Students in Performance Band 1 array(lowest) in Language",
'98' => "Number of Students in Performance Band 2 in Language",
'99' => "Number of Students in Performance Band 3 in Language",
'100' => "Number of Students in Performance Band 4 in Language",
'101' => "Number of Students in Performance Band 5 array(highest) in Language",
'1097' => "Percent Students in Performance Band 1 array(lowest) in Language",
'1098' => "Percent Students in Performance Band 2 in Language",
'1099' => "Percent Students in Performance Band 3 in Language",
'1100' => "Percent Students in Performance Band 4 in Language",
'1101' => "Percent Students in Performance Band 5 array(highest) in Language",

'102' => "Number of Students in Performance Band 1 array(lowest) in Spelling",
'103' => "Number of Students in Performance Band 2 in Spelling",
'104' => "Number of Students in Performance Band 3 in Spelling",
'105' => "Number of Students in Performance Band 4 in Spelling",
'106' => "Number of Students in Performance Band 5 array(highest) in Spelling",
'1102' => "Percent Students in Performance Band 1 array(lowest) in Spelling",
'1103' => "Percent Students in Performance Band 2 in Spelling",
'1104' => "Percent Students in Performance Band 3 in Spelling",
'1105' => "Percent Students in Performance Band 4 in Spelling",
'1106' => "Percent Students in Performance Band 5 array(highest) in Spelling",

'107' => "Number of Students in Performance Band 1 array(lowest) in Science",
'108' => "Number of Students in Performance Band 2 in Science",
'109' => "Number of Students in Performance Band 3 in Science",
'110' => "Number of Students in Performance Band 4 in Science",
'111' => "Number of Students in Performance Band 5 array(highest) in Science",
'1107' => "Percent Students in Performance Band 1 array(lowest) in Science",
'1108' => "Percent Students in Performance Band 2 in Science",
'1109' => "Percent Students in Performance Band 3 in Science",
'1110' => "Percent Students in Performance Band 4 in Science",
'1111' => "Percent Students in Performance Band 5 array(highest) in Science",

'112' => "Number of Students in Performance Band 1 array(lowest) in Social Science",
'113' => "Number of Students in Performance Band 2 in Social Science",
'114' => "Number of Students in Performance Band 3 in Social Science",
'115' => "Number of Students in Performance Band 4 in Social Science",
'116' => "Number of Students in Performance Band 5 array(highest) in Social Science",
'1112' => "Percent Students in Performance Band 1 array(lowest) in Social Science",
'1113' => "Percent Students in Performance Band 2 in Social Science",
'1114' => "Percent Students in Performance Band 3 in Social Science",
'1115' => "Percent Students in Performance Band 4 in Social Science",
'1116' => "Percent Students in Performance Band 5 array(highest) in Social Science",
),

"7" => array(
'117' => "API for African American Subgroup",
'118' => "Number of Students Tested in African American Subgroup",
'119' => "African American Subgroup -- Number of",
'120' => "African American Subgroup -- Number of Students in Performance Band 2 in Reading",
'121' => "African American Subgroup -- Number of Students in Performance Band 3 in Reading",
'122' => "African American Subgroup -- Number of Students in Performance Band 4 in Reading",
'123' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'124' => "African American Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'125' => "African American Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'126' => "African American Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'127' => "African American Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'128' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'129' => "African American Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'130' => "African American Subgroup -- Number of Students in Performance Band 2 in Language",
'131' => "African American Subgroup -- Number of Students in Performance Band 3 in Language",
'132' => "African American Subgroup -- Number of Students in Performance Band 4 in Language",
'133' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'134' => "African American Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'135' => "African American Subgroup -- Number of Students in Performance Band 2 in Spelling",
'136' => "African American Subgroup -- Number of Students in Performance Band 3 in Spelling",
'137' => "African American Subgroup -- Number of Students in Performance Band 4 in Spelling",
'138' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'139' => "African American Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'140' => "African American Subgroup -- Number of Students in Performance Band 2 in Science",
'141' => "African American Subgroup -- Number of Students in Performance Band 3 in Science",
'142' => "African American Subgroup -- Number of Students in Performance Band 4 in Science",
'143' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'144' => "African American Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'145' => "African American Subgroup -- Number of Students in Performance Band 2 in Social Science",
'146' => "African American Subgroup -- Number of Students in Performance Band 3 in Social Science",
'147' => "African American Subgroup -- Number of Students in Performance Band 4 in Social Science",
'148' => "African American Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"8" => array(
'149' => "API for American Indian Subgroup",
'150' => "Number of Students Tested in American Indian Subgroup",
'151' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'152' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Reading",
'153' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Reading",
'154' => "American Indian Subgroup -- Number of Students in Performance Band 4 in Reading",
'155' => "American Indian Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'156' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'157' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'158' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'159' => "American Indian Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'160' => "American Indian Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'161' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'162' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Language",
'163' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Language",
'164' => "American Indian Subgroup -- Number of Students in Performance Band 4 in Language",
'165' => "American Indian Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'166' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'167' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Spelling",
'168' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Spelling",
'169' => "American Indian Subgroup -- Number of Students in Performance Band 4 in Spelling",
'170' => "American Indian Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'171' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'172' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Science",
'173' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Science",
'174' => "American Indian Subgroup -- Number of Students in Performance Band 4 in Science",
'175' => "American Indian Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'176' => "American Indian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'177' => "American Indian Subgroup -- Number of Students in Performance Band 2 in Social Science",
'178' => "American Indian Subgroup -- Number of Students in Performance Band 3 in Social Science",
'179' => "American Indian Subgroup - Number of Students in Performance Band 4 in Social Science",
'180' => "American Indian Subgroup - Number of Students in Performance Band 5 array(highest) in Social Science",
),

"9" => array(
'181' => "API for Asian Subgroup",
'182' => "Number of Students Tested in Asian Subgroup",
'183' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'184' => "Asian Subgroup -- Number of Students in Performance Band 2 in Reading",
'185' => "Asian Subgroup -- Number of Students in Performance Band 3 in Reading",
'186' => "Asian Subgroup -- Number of Students in Performance Band 4 in Reading",
'187' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'188' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'189' => "Asian Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'190' => "Asian Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'191' => "Asian Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'192' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'193' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'194' => "Asian Subgroup -- Number of Students in Performance Band 2 in Language",
'195' => "Asian Subgroup -- Number of Students in Performance Band 3 in Language",
'196' => "Asian Subgroup -- Number of Students in Performance Band 4 in Language",
'197' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'198' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'199' => "Asian Subgroup -- Number of Students in Performance Band 2 in Spelling",
'200' => "Asian Subgroup -- Number of Students in Performance Band 3 in Spelling",
'201' => "Asian Subgroup -- Number of Students in Performance Band 4 in Spelling",
'202' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'203' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'204' => "Asian Subgroup -- Number of Students in Performance Band 2 in Science",
'205' => "Asian Subgroup -- Number of Students in Performance Band 3 in Science",
'206' => "Asian Subgroup -- Number of Students in Performance Band 4 in Science",
'207' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'208' => "Asian Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'209' => "Asian Subgroup -- Number of Students in Performance Band 2 in Social Science",
'210' => "Asian Subgroup -- Number of Students in Performance Band 3 in Social Science",
'211' => "Asian Subgroup -- Number of Students in Performance Band 4 in Social Science",
'212' => "Asian Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",

),

"10" => array(
'213' => "API for Filipino Subgroup",
'214' => "Number of Students Tested in Filipino Subgroup",
'215' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'216' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Reading",
'217' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Reading",
'218' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Reading",
'219' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'220' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'221' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'222' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'223' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'224' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'225' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'226' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Language",
'227' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Language",
'228' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Language",
'229' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'230' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'231' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Spelling",
'232' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Spelling",
'233' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Spelling",
'234' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'235' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'236' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Science",
'237' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Science",
'238' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Science",
'239' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'240' => "Filipino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'241' => "Filipino Subgroup -- Number of Students in Performance Band 2 in Social Science",
'242' => "Filipino Subgroup -- Number of Students in Performance Band 3 in Social Science",
'243' => "Filipino Subgroup -- Number of Students in Performance Band 4 in Social Science",
'244' => "Filipino Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"11" => array(
'245' => "API for Hispanic or Latino Subgroup",
'246' => "Number of Students Tested in Hispanic or Latino Subgroup",
'247' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'248' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Reading",
'249' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Reading",
'250' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Reading",
'251' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'252' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'253' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'254' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'255' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'256' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'257' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'258' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Language",
'259' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Language",
'260' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Language",
'261' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'262' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'263' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Spelling",
'264' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Spelling",
'265' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Spelling",
'266' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'267' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'268' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Science",
'269' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Science",
'270' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Science",
'271' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'272' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'273' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 2 in Social Science",
'274' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 3 in Social Science",
'275' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 4 in Social Science",
'276' => "Hispanic or Latino Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"12" => array(
'277' => "API for Pacific Islander Subgroup",
'278' => "Number of Students Tested in Pacific Islander Subgroup",
'279' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'280' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Reading",
'281' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Reading",
'282' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Reading",
'283' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'284' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'285' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'286' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'287' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'288' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'289' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'290' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Language",
'291' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Language",
'292' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Language",
'293' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'294' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'295' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Spelling",
'296' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Spelling",
'297' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Spelling",
'298' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'299' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'300' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Science",
'301' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Science",
'302' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Science",
'303' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'304' => "Pacific Islander Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'305' => "Pacific Islander Subgroup -- Number of Students in Performance Band 2 in Social Science",
'306' => "Pacific Islander Subgroup -- Number of Students in Performance Band 3 in Social Science",
'307' => "Pacific Islander Subgroup -- Number of Students in Performance Band 4 in Social Science",
'308' => "Pacific Islander Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"13" => array(
'309' => "API for White not Hispanic Subgroup",
'310' => "Number of Students Tested in White not Hispanic Subgroup",
'311' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'312' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Reading",
'313' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Reading",
'314' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Reading",
'315' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",
'316' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'317' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'318' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'319' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'320' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'321' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",
'322' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Language",
'323' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Language",
'324' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Language",
'325' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'326' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",
'327' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Spelling",
'328' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Spelling",
'329' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Spelling",
'330' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'331' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'332' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Science",
'333' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Science",
'334' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Science",
'335' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'336' => "White not Hispanic Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'337' => "White not Hispanic Subgroup -- Number of Students in Performance Band 2 in Social Science",
'338' => "White not Hispanic Subgroup -- Number of Students in Performance Band 3 in Social Science",
'339' => "White not Hispanic Subgroup -- Number of Students in Performance Band 4 in Social Science",
'340' => "White not Hispanic Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"14" => array(
'341' => "API for Socioeconomically Disadvantaged Subgroup",
'342' => "Number of Students Tested in Socioeconomically Disadvantaged Subgroup",
'343' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Reading",
'344' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Reading",
'345' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Reading",
'346' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Reading",
'347' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Reading",'348' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Mathematics",
'349' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Mathematics",
'350' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Mathematics",
'351' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Mathematics",
'352' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Mathematics",
'353' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Language",'354' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Language",
'355' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Language",
'356' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Language",
'357' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Language",
'358' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Spelling",'359' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Spelling",
'360' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Spelling",
'361' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Spelling",
'362' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Spelling",
'363' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Science",
'364' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Science",
'365' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Science",
'366' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Science",
'367' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Science",
'368' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 1 array(lowest) in Social Science",
'369' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 2 in Social Science",
'370' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 3 in Social Science",
'371' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 4 in Social Science",
'372' => "Socioeconomically Disadvantaged Subgroup -- Number of Students in Performance Band 5 array(highest) in Social Science",
),

"15" => array(
'55' => "Percent of Students African American",
'56' => "Percent of Students American Indian",
'57' => "Percent of Students Asian",
'58' => "Percent of Students Filipino",
'59' => "Percent of Students Hispanic or Latino",
'60' => "Percent of Students Pacific Islander",
'61' => "Percent of Students White",
'62' => "Percent of Students Multiple or No Response",
'63' => "Percent of Students Participating in the Free or Reduced Price Lunch Program",
'64' => "Percent of Students English Language Learners",
)

);
?>