<?php

$comAgg = array(
"01" => "Live Animals",
"02" => "Meat & Edible Meat",
"03" => "Fish & Crustaceans => Molluscs & Other Aquatic Invertebrates",
"04" => "Dairy Produce; Birds' Eggs; Natural Honey; Other Edible Products Of Animal Origin",
"05" => "Products Of Animal Origin => Nesoi",
"06" => "Live Trees & Other Plants; Bulbs => Roots; Cut Flowers & Ornamental Foliage",
"07" => "Edible Vegetables & Certain Roots & Tubers",
"08" => "Edible Fruit & Nuts; Peel Of Citrus Fruit Or Melons",
"09" => "Coffee => Tea => Mate & Spices",
"10" => "Cereals",
"11" => "Milling Industry Products; Malt; Starches; Inulin; Wheat Gluten",
"12" => "Oil Seeds; Misc. Grains => Seeds & Fruits; Industrial Or Medicinal Plants",
"13" => "Lac; Gums; Resins & Other Vegetable Saps & Extracts",
"14" => "Vegetable Plaiting Materials & Vegetable Products => Nesoi",
"15" => "Animal Or Vegetable Fats & Oils; Prepared Edible Fats; Animal Or Vegetable Waxes",
"16" => "Edible Preparations Of Meat => Fish => Crustaceans => Molluscs Or Other Aquatic Invertebrates",
"17" => "Sugars & Sugar Confectionary",
"18" => "Cocoa & Cocoa Preparations",
"19" => "Preparations Of Cereals => Flour => Starch Or Milk; Bakers' Wares",
"20" => "Preparations Of Vegetables => Fruit => Nuts => Or Other Parts Of Plants",
"21" => "Misc. Edible Preparations",
"22" => "Beverages => Spirits & Vinegar",
"23" => "Residues & Waste From The Food Industries; Prepared Animal Feed",
"24" => "Tobacco & Manufactured Tobacco Substitutes",
"25" => "Salt; Sulfur; Earths & Stone; Plastering Materials => Lime & Cement",
"26" => "Ores => Slag & Ash",
"27" => "Mineral Fuels => Mineral Oils; Bituminous Substances; Mineral Waxes",
"28" => "Inorganic Chemicals; Organic Or Inorganic Compounds Except Organic Chemicals",
"29" => "Organic Chemicals",
"30" => "Pharmaceutical Products",
"31" => "Fertilizers",
"32" => "Tanning Or Dyeing Extracts; Coloring Matter; Paints & Varnishes; Putty",
"33" => "Essential Oils & Resinoids; Perfumery => Cosmetic Or Toilet Preparations",
"34" => "Soap; Waxes => Polishing Or Scouring Products; Candles; Dental Preparations",
"35" => "Albuminoidal Substances; Modified Starches; Glues; Enzymes",
"36" => "Explosives; Pyrotechnic Products",
"37" => "Photographic Or Cinematographic Goods",
"38" => "Misc. Chemical Products",
"39" => "Plastics & Articles Thereof",
"40" => "Rubber & Articles Thereof",
"41" => "Raw Hides & Skins (Other Than Furskins) & Leather",
"42" => "Articles Of Leather And Of Gut (Other Than Silkworm Gut)",
"43" => "Furskins & Artificial Fur; Manufactures Thereof",
"44" => "Wood & Articles Of Wood; Wood Charcoal",
"45" => "Cork & Articles Of Cork",
"46" => "Manufactures Of Straw Or Other Plaiting Materials",
"47" => "Pulp; Recovered (Waste And Scrap) Paper And Paperboard",
"48" => "Paper & Paperboard; Articles Of Paper Pulp",
"49" => "Printed Books => Newspapers => Pictures & Other Printed Products",
"50" => "Silk => Including Yarns & Woven Fabrics Thereof",
"51" => "Wool => Yarns & Woven Fabrics Thereof",
"52" => "Cotton",
"53" => "Misc. Vegetable Textile Fibers => Yarns & Woven Fabrics",
"54" => "Manmade Filaments => Including Yarns & Woven Fabrics Thereof",
"55" => "Manmade Staple Fibers => Including Yarns & Woven Fabrics Thereof",
"56" => "Wadding => Felt & Nonwovens; Special Yarns; Twine => Cordage => Ropes & Cables",
"57" => "Carpets & Other Textile Floor Coverings",
"58" => "Special Woven Fabrics; Lace; Tapestries; Trimmings; Embroidery",
"59" => "Laminated Textile Fabrics; Textile Articles Suitable For Industrial Use",
"60" => "Knitted Or Crocheted Fabrics",
"61" => "Apparel & Clothing Accessories => Knitted Or Crocheted",
"62" => "Apparel & Clothing Accessories => Not Knitted Or Crocheted",
"63" => "Misc. Made-Up Textile Articles",
"64" => "Footwear => Gaiters & The Like; Parts Of Such Articles",
"65" => "Headgear & Parts Thereof",
"66" => "Umbrellas => Walking-Sticks => Seat-sticks => Whips => Riding-crops",
"67" => "Prepared Feathers & Down; Artificial Flowers; Articles Of Human Hair",
"68" => "Articles Of Stone => Plaster => Cement => Asbestos => Mica Or Similar Materials",
"69" => "Ceramic Products",
"70" => "Glass & Glassware",
"71" => "Pearls => Precious Or Semiprecious Stones => Precious Metals; Imitation Jewelry; Coins",
"72" => "Iron & Steel",
"73" => "Articles Of Iron Or Steel",
"74" => "Copper & Articles Thereof",
"75" => "Nickel & Articles Thereof",
"76" => "Aluminum & Articles Thereof",
"78" => "Lead & Articles Thereof",
"79" => "Zinc & Articles Thereof",
"80" => "Tin & Articles Thereof",
"81" => "Base Metals Nesoi; Cermets; Articles Thereof",
"82" => "Tools => Implements => Cutlery => Spoons & Forks => Of Base Metal",
"83" => "Misc. Articles Of Base Metal",
"84" => "Nuclear Reactors => Boilers => Machinery & Mechanical Appliances",
"85" => "Electrical Machinery; Sound Recorders => Television Recorders => Parts & Accessories",
"86" => "Railway Or Tramway Locomotives => Track Fixtures & Fittings; Traffic Signal Equipment",
"87" => "Vehicles Other Than Railway Or Tramway Rolling Stock",
"88" => "Aircraft => Spacecraft => & Parts Thereof",
"89" => "Ships => Boats & Floating Structures",
"90" => "Optical => Photographic => Cinematographic => Measuring => Medical Instruments",
"91" => "Clocks & Watches & Parts Thereof",
"92" => "Musical Instruments; Parts & Accessories Thereof",
"93" => "Arms & Ammunition; Parts & Accessories Thereof",
"94" => "Furniture; Lamps & Lighting Fittings; Illuminated Signs; Prefabricated Buildings",
"95" => "Toys => Games & Sports Equipment; Parts & Accessories Thereof",
"96" => "Misc. Manufactured Articles",
"97" => "Works Of Art => Collectors' Pieces & Antiques",
"98" => "Special Classification Provisions => Nesoi",
"99" => "Special Import Reporting Provisions => Nesoi"
);

$areasArray = array(99 => "U.S.",
"31" => "Anchorage Alaska",
"13" => "Baltimore M.D.",
"4" => "Boston Mass.",
"9" => "Buffalo N.Y.",
"16" => "Charleston S.C.",
"39" => "Chicago Ill.",
"41" => "Cleveland Ohio",
"29" => "Columbia-Snake",
"55" => "Dallas/Fort Worth, Texas",
"38" => "Detroit Mich.",
"36" => "Duluth Minn.",
"24" => "El Paso Tex.",
"33" => "Great Falls Mont.",
"32" => "Honolulu Hawaii",
"53" => "Houston Tex.",
"23" => "Laredo Tex.",
"27" => "Los Angeles",
"52" => "Miami Fla.",
"37" => "Milwaukee Wis.",
"35" => "Minneapolis Minn.",
"19" => "Mobile Ala.",
"20" => "New Orleans La.",
"10" => "New York City N.Y.",
"26" => "Nogales Ariz.",
"14" => "Norfolk Va.",
"7" => "Ogdensburg N.Y.",
"34" => "Pembina N. Dak.",
"11" => "Philadelphia Pa.",
"21" => "Port Arthur Tex.",
"1" => "Portland Maine",
"5" => "Providence R.I.",
"25" => "San Diego",
"28" => "San Francisco",
"49" => "San Juan Puerto Rico",
"17" => "Savannah Ga.",
"30" => "Seattle Wash.",
"70" => "Shipments Individually",
"2" => "St. Albans Vt.",
"45" => "St. Louis Mo.",
"18" => "Tampa Fla.",
"60" => "Vessels Own Power",
"51" => "Virgin Islands",
"54" => "Washington D.C.",
"15" => "Wilmington N.C."
);

?>