<?php
/******************************************
* @Modified on March 20, 2012
* @Package: Rand
* @Developer: Baljinder Singh
* @URL : http://www.ideafoundation.in
********************************************/

$basedir=dirname(__FILE__)."/../..";
include_once $basedir."/include/headerHtml.php";
?>

 <!-- container -->
<section id="container">

	<section class="conatiner-full" id="inner-content">
	<h2>RAND Texas Non-Residential Vacancy Statistics Background</h2>
	
	<p>&nbsp;</p>
	<p>Non-residential vacancy statistics contains office vacancy rates for the U.S., Texas, and Texas metropolitan areas. Vacancy rates are presented for downtown, metropolitan, and suburban areas. The source for these data (except Texas average, which is generated by RAND Texas) is CB Richard Ellis.</p>

	<p>&nbsp;</p>

	<p>CB Richard Ellis vacancy rates are based on a quarterly survey of major office buildings. Each rate is computed as a percentage, dividing vacant space for lease by the total square footage of office space in each area. The index covers major competitive multi-tenant office buildings. It excludes government-owned, medical, office condominiums and those that are not competitive in today's marketplace. The majority of the buildings have been constructed since WWII, although those that have been renovated are also included. Newly constructed buildings are added to the survey upon completion.</p>

	<p>&nbsp;</p>

	<p>The downtown rate typically covers office buildings in the central core of the largest city within the metropolitan area. The corresponding suburban area includes the remainder of the metropolitan area (excluding the central core). (In a few metropolitan areas, there is no single major central core area.)</p> 
	</section>

</section>

<?php include_once $basedir."/include/footerHtml.php"; ?>